### ISSUE TITLE
feedback จากtester

### ISSUE THREAD

**Issue by mon9k0rn** [ThanichaMongkorn/-#12]

**Comment by mon9k0rn** [comment]
![image](https://user-images.githubusercontent.com/110970224/191340443-2b974b60-3a12-4196-a7e7-6ee15b77a769.png)

**Comment by Kitsunegakawaiinee** [comment]
ยังมีบัคอยู่นะ 
-กดตีได้ในฉากแรก
-ตกลาวาแล้วโดดขึ้นไม่ได้
-โดดไปเหยียบแป้นเหยียบไม่ได้
-เปิดประตูไท่ได้บายนึง
