### ISSUE TITLE
รายงานความคืบหน้าและความชัดเจนของstoryboard

### ISSUE THREAD

**Issue by mon9k0rn** [ThanichaMongkorn/-#8]

**Comment by touchtt0205** [comment]
![Uploading 788AB8A0-1365-486C-B206-0DAF70DFF091.png…]()

**Comment by touchtt0205** [comment]
![IMG_8387](https://user-images.githubusercontent.com/110968457/189842519-b36ca778-5aa3-4029-997b-8140c2b1f329.png)

**Comment by touchtt0205** [comment]
ตัวละคร

**Comment by mon9k0rn** [comment]
โอเชช
