### ISSUE TITLE
รายงานความคืบหน้าตัวโปรแกรม

### ISSUE THREAD

**Issue by mon9k0rn** [ThanichaMongkorn/-#9]

**Comment by jamess66** [comment]
https://scratch.mit.edu/projects/722504608
เคลื่อนที่ + ตรวจจับการชน + กระโดด +โจมตี + อนิเมชั่น

**Comment by jamess66** [comment]
https://scratch.mit.edu/projects/722504608
health system + combat system(แค่โดนโจมตี+ตาย)

**Comment by mon9k0rn** [comment]
okkkมะกี้เราลองเล่นดูละสุดยอดเลยเก่งมากๆ

**Comment by Kitsunegakawaiinee** [comment]
ระบบดีแล้วครับ แต่ตอน restart อย่าลืม set position ให้อยู่ในที่ปลอดภัยด้วยนะครับ
